
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
CandyCrush = { path = "../game", default-features = false }

[features]
default = ["CandyCrush/default"]
dylib-engine = ["CandyCrush/dylib-engine"]
